### ISSUE TITLE
Restricting access for new members

### ISSUE THREAD

**Issue by JFBM** [Worldbuilding-Workshop/Information-and-Tutorials#1]
I would say that only users who were active for a long time should be considered for access to every repository. New members have to request access to every repository individually to prevent vandalism.

**Comment by ArtOfCode-** [comment]
Add my voice to this proposal. As long as this can be done efficiently using the organization, this is a good idea. We have enough in our core team to cover much of the day.

**Comment by ArtOfCode-** [comment]
I'm taking care of this - we're organising teams and hierarchy for managing the project.

**Comment by ArtOfCode-** [comment]
Complete - both the team structure and instructions document reflect the updates.
